### ISSUE TITLE
Interfaces and base classes are missing in the class diagram

### ISSUE THREAD

**Issue by krisztianb** [krisztianb/typedoc-umlclass#11]
Dear @krisztianb 

### umlclass diagram

![image](https://user-images.githubusercontent.com/6151258/82385096-96111b80-9a31-11ea-9fb3-8afb2db5b0eb.png)

### uml vscode diagram

![image](https://user-images.githubusercontent.com/6151258/82385085-91e4fe00-9a31-11ea-88e4-71b47b74bb58.png)

I see now from the previous picture sent,  a better decode of the type but I don't have all the dependencies that means interface, inheritance are missing.

Best Regards,
Youssef

_Originally posted by @yboujraf in https://github.com/krisztianb/typedoc-umlclass/issues/6#issuecomment-631123738_

**Comment by krisztianb** [comment]
Dear @yboujraf

To which class does the first image belong to? CommandBase or AllDestinationsAssociationNamesRequestMessageCommand?

Why is CommandBase class is not there in the second image?

**Comment by yboujraf** [comment]
Dear @krisztianb 

The image belongs to  "AllDestinationsAssociationNamesRequestMessageCommand"

### I have 4 files included in a folder 

![image](https://user-images.githubusercontent.com/6151258/82592551-64b75d80-9ba1-11ea-879e-418077cd44d6.png)

### using tools to generae uml

![image](https://user-images.githubusercontent.com/6151258/82592623-7bf64b00-9ba1-11ea-8fbd-0af02f0f78cb.png)

### scanning

![image](https://user-images.githubusercontent.com/6151258/82592662-8b759400-9ba1-11ea-81a6-d3b0190687a2.png)

### finally, the diagram

![image](https://user-images.githubusercontent.com/6151258/82592724-a3e5ae80-9ba1-11ea-9ece-e0676dd684a1.png)


The basecommand is not included because not on the same folder otherwise I can generate the whole uml of the project.

Best regards,
Youssef

Best Regards

**Comment by krisztianb** [comment]
Dear @yboujraf 

Can you explain to me what the dashed arrows in the diagram mean? Are those base classes that the AllDestinationsAssociationNamesRequestMessageCommand class is extending and interfaces it is implementing?

So that AllDestinationsAssociationNamesRequestMessageCommand:

extends
* CommandOptionsUtility
* CommandOptionsValidator (only visible on your first screenshot, but not on the last one)
* CommandParamsUtility
* CommandParamsValidator

and implements
* AllDestinationsAssociationNamesRequestMessageCommandOptions
* AllDestinationsAssociationNamesRequestMessageCommandParams

Which would be kind of odd, since a class can only have one base class in TypeScript.

**Comment by yboujraf** [comment]
Dear @krisztianb 

Could you share your private email, I will send you my project for better test if you want otherwise we will play ping pong long indefintely ;-)

Besty regards,
Youssef

**Comment by krisztianb** [comment]
Dear @yboujraf I added the address to my GitHub profile.

**Comment by krisztianb** [comment]
Fixed in 0.1.6 🎉
